name: mock_interviewer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1=cpu*
  - spacy=3.8.7
  - flask=3.1.1
  - ffmpeg=7.1.0
  - pip=23.1.2
  - pip:
    - openai-whisper==20230314
    - transformers==4.30.0
    - PyPDF2==3.0.1
    - python-dotenv==1.0.0
    - flask-cors==4.0.0
    - gunicorn==21.2.0